### ISSUE TITLE
App crashes when importing labels with either COCO JSON or Yolov8 files

### ISSUE THREAD

**Issue by AJ-learning** [bnsreenu/digitalsreeni-image-annotator#11]
Tested this issue multiple times on different files. It's confirmed. 

I have labels that I want to import. The labels are rectangles bounding boxes. The app crashes unexpectedly when attempting to import the file. 

The error is in the function "area = calculate_area(annotation)" in the "utils.py" script. From my understanding, the area calculator expects to calculate the area based on a segmentation file. If the file does not include segments, then it crashes. My files are all bounding boxes. 

In addition to fixing the import error, it would be nice if the app gives an error message instead of crashing in the future if anything else happens unexpectedly

Here's the error message from cmd. I have also included test files to replicate the error.

Switching to image: test.png
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\ds-img-annot\lib\site-packages\digitalsreeni_image_annotator\annotator_window.py", line 263, in open_project
    self.open_specific_project(project_file)
  File "C:\Users\user\Anaconda3\envs\ds-img-annot\lib\site-packages\digitalsreeni_image_annotator\annotator_window.py", line 339, in open_specific_project
    self.switch_image(self.image_list.item(0))
  File "C:\Users\user\Anaconda3\envs\ds-img-annot\lib\site-packages\digitalsreeni_image_annotator\annotator_window.py", line 1062, in switch_image
    self.update_annotation_list()
  File "C:\Users\user\Anaconda3\envs\ds-img-annot\lib\site-packages\digitalsreeni_image_annotator\annotator_window.py", line 1736, in update_annotation_list
    area = calculate_area(annotation)
  File "C:\Users\user\Anaconda3\envs\ds-img-annot\lib\site-packages\digitalsreeni_image_annotator\utils.py", line 15, in calculate_area
    x, y = annotation["segmentation"][0::2], annotation["segmentation"][1::2]
TypeError: 'NoneType' object is not subscriptable

----
Attachments

Sorry the image is a high resolution one, but I deleted most of it for confidentiality. The only area I kept is where the label is expected.
 
[COCOtest.json](https://github.com/user-attachments/files/17740108/COCOtest.json)
![test](https://github.com/user-attachments/assets/4bdf9fb0-56ab-4864-a7c4-1a1aa175d09d)
[YOLODatasetV8.zip](https://github.com/user-attachments/files/17740366/YOLODatasetV8.zip)

**Comment by bnsreenu** [comment]
Thanks for reporting, let me check and fix the issue. The export from this application always includes area which is why the import is also designed to include it. I did not test it for external annotations that may not include all the parameters that this application expects.

**Comment by bnsreenu** [comment]
Unable to reproduce, can you please point me to a public dataset that I can use to reproduce the issue?

**Comment by bnsreenu** [comment]
Fixed the issue in 0.8.6.
